"use client";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";

export default function NewNote(){
 const [cats,setCats]=useState<any[]>([]);const [form,setForm]=useState({slug:"",title_en:"",title_as:"",excerpt_en:"",excerpt_as:"",content_en:"",content_as:"",category_id:"",published:false});const [pdf,setPdf]=useState<File|null>(null);const [msg,setMsg]=useState("");const router=useRouter();
 useEffect(()=>{createClient().from("categories").select("id,name_en").eq("type","note").then(({data})=>setCats(data||[]))},[]);
 const set=(k:string,v:any)=>setForm(f=>({...f,[k]:v}));
 async function submit(e:React.FormEvent){e.preventDefault();setMsg("Saving…");const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){setMsg("Login required");return}
 let pdf_path=null;if(pdf){pdf_path=`${user.id}/${Date.now()}-${pdf.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const up=await s.storage.from("notes-pdfs").upload(pdf_path,pdf);if(up.error){setMsg(up.error.message);return}}
 const {error}=await s.from("notes").insert({...form,pdf_path,created_by:user.id});if(error)setMsg(error.message);else{router.push("/admin/notes");router.refresh()}}
 return <div className="page"><div className="container"><span className="badge">CMS / NEW NOTE</span><h1 className="page-title">Create Note</h1><form className="form" onSubmit={submit}><div className="two-col"><Field label="Slug"><input className="input" required value={form.slug} onChange={e=>set("slug",e.target.value)}/></Field><Field label="Category"><select className="select" value={form.category_id} onChange={e=>set("category_id",e.target.value)}><option value="">Select category</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name_en}</option>)}</select></Field></div><div className="two-col"><Field label="English title"><input className="input" required value={form.title_en} onChange={e=>set("title_en",e.target.value)}/></Field><Field label="Assamese title"><input className="input" value={form.title_as} onChange={e=>set("title_as",e.target.value)}/></Field></div><div className="two-col"><Field label="English excerpt"><textarea className="textarea" value={form.excerpt_en} onChange={e=>set("excerpt_en",e.target.value)}/></Field><Field label="Assamese excerpt"><textarea className="textarea" value={form.excerpt_as} onChange={e=>set("excerpt_as",e.target.value)}/></Field></div><div className="two-col"><Field label="English content"><textarea className="textarea" style={{minHeight:260}} value={form.content_en} onChange={e=>set("content_en",e.target.value)}/></Field><Field label="Assamese content"><textarea className="textarea" style={{minHeight:260}} value={form.content_as} onChange={e=>set("content_as",e.target.value)}/></Field></div><Field label="PDF"><input className="input" type="file" accept="application/pdf" onChange={e=>setPdf(e.target.files?.[0]||null)}/></Field><label><input type="checkbox" checked={form.published} onChange={e=>set("published",e.target.checked)}/> Publish immediately</label>{msg&&<div className="notice">{msg}</div>}<button className="btn primary">Save Note</button></form></div></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div><label className="label">{label}</label>{children}</div>}
