"use client";
import { useEffect,useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";

export default function NewTest(){
 const [qs,setQs]=useState<any[]>([]);const [form,setForm]=useState({title_en:"",title_as:"",description_en:"",description_as:"",duration_minutes:30,published:false});const [selected,setSelected]=useState<string[]>([]);const [msg,setMsg]=useState("");const router=useRouter();
 useEffect(()=>{createClient().from("questions").select("id,question_en").order("created_at",{ascending:false}).then(({data})=>setQs(data||[]))},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setMsg("Saving…");const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return setMsg("Login required");const {data:test,error}=await s.from("tests").insert({...form,created_by:user.id}).select("id").single();if(error||!test)return setMsg(error?.message||"Could not create test");if(selected.length){const {error:e2}=await s.from("test_questions").insert(selected.map((question_id,position)=>({test_id:test.id,question_id,position:position+1})));if(e2)return setMsg(e2.message)}router.push("/admin/tests")}
 return <div className="page"><div className="container"><span className="badge">TEST BUILDER / NEW</span><h1 className="page-title">Create Test</h1><form className="form"><input className="input" required placeholder="English title" value={form.title_en} onChange={e=>setForm({...form,title_en:e.target.value})}/><input className="input" placeholder="Assamese title" value={form.title_as} onChange={e=>setForm({...form,title_as:e.target.value})}/><textarea className="textarea" placeholder="Description" value={form.description_en} onChange={e=>setForm({...form,description_en:e.target.value})}/><input className="input" type="number" min={1} value={form.duration_minutes} onChange={e=>setForm({...form,duration_minutes:Number(e.target.value)})}/><label><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/> Publish</label><h3>Select questions</h3><div className="card">{qs.map(q=><label className="option" key={q.id}><input type="checkbox" checked={selected.includes(q.id)} onChange={e=>setSelected(x=>e.target.checked?[...x,q.id]:x.filter(id=>id!==q.id))}/><span>{q.question_en}</span></label>)}</div>{msg&&<div className="notice">{msg}</div>}<button className="btn primary" onClick={submit}>Create Test</button></form></div></div>
}
