"use client";
import { useEffect,useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";

export default function NewQuestion(){
 const [cats,setCats]=useState<any[]>([]);const [q,setQ]=useState({question_en:"",question_as:"",options:["","","",""],correct_index:0,explanation_en:"",explanation_as:"",category_id:"",difficulty:"medium"});const [msg,setMsg]=useState("");const router=useRouter();
 useEffect(()=>{createClient().from("categories").select("id,name_en").then(({data})=>setCats(data||[]))},[]);
 function set(k:string,v:any){setQ(x=>({...x,[k]:v}))}
 async function submit(e:React.FormEvent){e.preventDefault();setMsg("Saving…");const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return setMsg("Login required");const {error}=await s.from("questions").insert({...q,created_by:user.id});if(error)setMsg(error.message);else router.push("/admin/questions")}
 return <div className="page"><div className="container"><span className="badge">QUESTION BANK / NEW</span><h1 className="page-title">Add MCQ</h1><form className="form"><textarea className="textarea" required placeholder="Question (English)" value={q.question_en} onChange={e=>set("question_en",e.target.value)}/><textarea className="textarea" placeholder="Question (Assamese)" value={q.question_as} onChange={e=>set("question_as",e.target.value)}/>{q.options.map((o,i)=><input className="input" key={i} required placeholder={`Option ${i+1}`} value={o} onChange={e=>set("options",q.options.map((x,j)=>j===i?e.target.value:x))}/>)}<div className="two-col"><select className="select" value={q.correct_index} onChange={e=>set("correct_index",Number(e.target.value))}>{q.options.map((_,i)=><option key={i} value={i}>Correct option {i+1}</option>)}</select><select className="select" value={q.difficulty} onChange={e=>set("difficulty",e.target.value)}><option>easy</option><option>medium</option><option>hard</option></select></div><select className="select" value={q.category_id} onChange={e=>set("category_id",e.target.value)}><option value="">Category</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name_en}</option>)}</select><textarea className="textarea" placeholder="Explanation (English)" value={q.explanation_en} onChange={e=>set("explanation_en",e.target.value)}/><textarea className="textarea" placeholder="Explanation (Assamese)" value={q.explanation_as} onChange={e=>set("explanation_as",e.target.value)}/>{msg&&<div className="notice">{msg}</div>}<button className="btn primary" onClick={submit}>Save MCQ</button></form></div></div>
}
